version: "3.9"

services:
  lsi-megaraid-storage-manager:
    container_name: lsi-megaraid-storage-manager
    image: baptistecdr/lsi-megaraid-storage-manager:4.1.1@sha256:62f06562c69115aa6c94de2359ae6bb89309dce01cf1b83ad5975ee69488e56a
    privileged: true
    environment:
      - TZ=Europe/Paris
      - ROOT_PASSWORD=myrootpassword
      - DISPLAY=$DISPLAY
    volumes:
      - $HOME/.Xauthority:/root/.Xauthority
      - /tmp/.X11-unix:/tmp/.X11-unix
    network_mode: host
