version: "3.9"

services:
  lsi-megaraid-storage-manager:
    container_name: lsi-megaraid-storage-manager
    image: baptistecdr/lsi-megaraid-storage-manager:4.0.3@sha256:86a8f5ea8027699f80c3b511d37c7d6a6f23ba2f6e9a6103ed56581c278a9319
    privileged: true
    environment:
      - TZ=Europe/Paris
      - ROOT_PASSWORD=myrootpassword
      - DISPLAY=$DISPLAY
    volumes:
      - $HOME/.Xauthority:/root/.Xauthority
      - /tmp/.X11-unix:/tmp/.X11-unix
    network_mode: host
