version: "3.9"

services:
  lsi-megaraid-storage-manager:
    container_name: lsi-megaraid-storage-manager
    image: baptistecdr/lsi-megaraid-storage-manager:4.1.5@sha256:032cbfa6cca7f6302b18b6af291a484a0f8109ed228e5419fcac1e3436049af5
    privileged: true
    environment:
      - TZ=Europe/Paris
      - ROOT_PASSWORD=myrootpassword
      - DISPLAY=$DISPLAY
    volumes:
      - $HOME/.Xauthority:/root/.Xauthority
      - /tmp/.X11-unix:/tmp/.X11-unix
    network_mode: host
