version: "3.9"

services:
  lsi-megaraid-storage-manager:
    container_name: lsi-megaraid-storage-manager
    image: baptistecdr/lsi-megaraid-storage-manager:4.1.3@sha256:c9de490a61793be2c29d9d67f98e2f979662fb06af3fff18d1cb9961c4108bfe
    privileged: true
    environment:
      - TZ=Europe/Paris
      - ROOT_PASSWORD=myrootpassword
      - DISPLAY=$DISPLAY
    volumes:
      - $HOME/.Xauthority:/root/.Xauthority
      - /tmp/.X11-unix:/tmp/.X11-unix
    network_mode: host
